### ISSUE TITLE
How to find the page footer?

### ISSUE THREAD

**Issue by prehistoric-penguin** [galkahana/PDF-Writer#104]
Hi, I am new to this great library, I want to find the page footer of a PDF file then remove it.  After going through the document, I didn't find some method directly related, can you please give me some hints?

**Comment by galkahana** [comment]
well, it's not like there's a definition of what a "page footer" is in PDF, so  i cant really tell you how to remove it.

what do you mean by a page footer?
what do you mean by removing it?

**Comment by prehistoric-penguin** [comment]
Sorry for misleading, I want to implement some feature described in [this article](www.hpl.hp.com/techreports/2002/HPL-2002-129.pd). In short, i want to remove the page number in PDF papers.

We can make a un-precise  assume here :
* The last line in a page
* The line only contains a page number
* The page number equals previous page number plus one

**Comment by galkahana** [comment]
good luck :)

**Comment by prehistoric-penguin** [comment]
Thank you. 8-)

**Comment by galkahana** [comment]
[this](http://pdfhummus.com/post/156548561656/extracting-text-from-pdf-files) should help you. you need to port the code to use PDFWriter instead of its javascript counterpart, but it will give you all texts in a page and all their position.
should be easy then to realize "lines", and which line is at the bottom, and what's the text there.

**Comment by prehistoric-penguin** [comment]
Thank you so much.
