### ISSUE TITLE
How to use the library with a win64 application?

### ISSUE THREAD

**Issue by lorenzinetor** [galkahana/PDF-Writer#110]
As said in the title, is it possible to use your library in a 64bit application? If building with the instructions in the Wiki I get linker errors when trying to build the win64 project tht would use it, and the solution of the library can only be built with win32 (or x64, but I'm not sure if I can use it for my project instead of win64).

**Comment by galkahana** [comment]
of course it works with 64 bit. 
the error you are getting is because you built the library to 32 bits, i guess that's cause this is the default for your computer/dev env. then trying to link this with 64 bit, it refuses (rightfully so) . you need to compile the lib for 64 bit.
I did write this in my building instructions. a link:
https://github.com/galkahana/PDF-Writer/wiki/Building-and-running-samples#building-with-cmake

if you want more options, you can consult with cmake site.
good luck
