### ISSUE TITLE
Very hard to fork

### ISSUE THREAD

**Issue by maxkomarychev** [galkahana/PDF-Writer#164]
When opening website https://pdfhummus.com there is a ribbon on the top right corner inviting to fork the project but it's very hard to click as only bottom 1/4 is really clickable.

![hard-to-fork](https://user-images.githubusercontent.com/7002833/64237151-728a5d00-cf04-11e9-92a8-0176f41d67fd.gif)

**Comment by galkahana** [comment]
made it bigger ok. fn tumblr logo was blocking the fork click.

As for me stopping support for the library. I would be lying if i'd say my general moving away from supporting both this one and the hummusjs module wasn't at all about lame feedback i got and the fact that as far as i was concerned i wasn't getting any meaningful contribution (don't mean money...but it would have been nice to see someone developing a module to extract images or text or tables on top of the lib or add some support to image or font types in the library itself).

I bet the general depression I got from work at my currently previous employer and corona had to do with this as well. I also left the building committee. got very tired of people bitching and not doing anything and stuff falls on me.

Dear Max here didn't actually cause my decision. It was actually quite a funny comment. I Know Max and he's a jolly wonderful guy.

Time passed. Julian Hille (bless him) took over the JS module management with MuhammaraJS and this year finally we're seeing that people move away in bulk from the now derpecated-for-my-use-only HummusJS to his version. I also started looking at my various Hummus projects (cloud service, text extraction and this project) as a vehicle for studying stuff. Just now i decided to get better at cmake which is why I added packaging to this project. Uncle asked me to develop table extraction so i did (well...for the very small number of documents he brought and a few more i tested) so added some content there. used my cloud service playground around hummus as a method to study k8s cluster setup, deployment and support for observability...so i'm still around.

Project is a bit old though by now. So I don't expect to do much but those studies and implementing sudden urges...so i guess i'm still not going to provide too much support...but frankly seems like people are either managing...or just finding alternative solutions. world is happy again. well. it's damn miserable cause people are still busy bashing each other instead or working together to improve our life here on this planet, but at least less of their misery is about problem working with PDFHummus.

hmm. only wanted to say that you can click there now. haha.
