### ISSUE TITLE
Render PDF as Bitmap on Android

### ISSUE THREAD

**Issue by ffreality** [galkahana/PDF-Writer#199]
I am working on PDF importer plugin for Unreal Engine. Is it possible to convert a PDF file which located on memory as byte array to a bitmap file ?

**Comment by galkahana** [comment]
It would be possible to do that but this project is probably not what you'd wanna use for that job.
What you are looking for is a PDF renderer. I'd recommend you one but it's been a while since I needed one and back then it was the Adobe PDF Library, which is good but i'm sure there are free options there. look for "PDF Renderer".

This library is for the creation, modifying and parsing of PDF files. while you could use the parser to develop a renderer yourself, that would be quite a tedious job, and you'd want something that's already available. The parser for this library could instead be used for more lighter goals for parsing a PDF, like extracting text and images, and for the purpose of creating a new PDF with slight changes.
