### ISSUE TITLE
Any example use OpenGL to render PDF?

### ISSUE THREAD

**Issue by zeroxer** [galkahana/PDF-Writer#200]
- Parsing pdf use PDF-Writer.
- Rendering pdf use OpenGL.

**Comment by galkahana** [comment]
As for parsing PDF with PDF-Writer there are several examples I can provide. First there's the post I created about it in the project blog with several starters:
https://www.pdfhummus.com/post/45501628414/parsing-pdf-0

I also used the parser to create a text extraction tool. It parses the basic features of the document, like pages count and page media box (the page dimensions) as well as parses the content of the PDF file looking for text placement commands in order to understand what text is drawn there. I recently also added paths parsing for some very initial attempt at parsing table data. you can find the project here:
https://github.com/galkahana/pdf-text-extraction
I can provide more pointers there to how the parser is used.

This library has a NodeJS counterpart and the methods names are kinda similar, so if you want to read some node code to figure out what you can do here then there's also some examples of the parser in javascript, in particular here's one that parses form data from PDF:
https://github.com/galkahana/HummusJSSamples/blob/master/parsing-form-values/pdf-digital-form.js



As for rendering PDF to bitmap or to be used in opengl, then while the parser of this library could be potentially used to build a renderer, it sounds to me like a large project and there are existing libraries that can render PDF. Adobe PDF library is one example, and unfortunately the only one i used in the past, for javascript i'm familiar with [PDF.JS](https://github.com/mozilla/pdf.js). but if you will look for "PDF Renreder in XXXXX language" you will probably chance on a good option.

**Comment by zeroxer** [comment]
Thanks for your help. I'll try.
