### ISSUE TITLE
Missing lib.obj file

### ISSUE THREAD

**Issue by EbCoom** [galkahana/PDF-Writer#213]
I downloaded the zip-file, extracted it, build the project and afterwards used the install function to create the ect\install folder with all the includes and libraries. However when I then try to link this project to one of my own project in visual studio I always get the message a certain file is missing: "lib.obj" should be in the install map according to visual studio, but it can't find it and i checked and indeed it isn't there. What am I doing wrong?

**Comment by galkahana** [comment]
that doesn't sound right to me. once building the lib you should be getting static libs .lib files (or + dll if compiled to shared files) and at this point should need only them. Defo not any obj files (i mean from the library, sure your code still compiled to .obj). So it might be that how the project links to the lib files might be wrong. make sure to link to them, and use the headers as search libs, but don't try to compile them.
if you can recreate this with a small project and send it to me maybe i can have a look and see what's wrong.

**Comment by EbCoom** [comment]
You can find a zip-file of my project at the following link: Filehandler.zip<https://vub-my.sharepoint.com/:u:/g/personal/ebe_coomans_vub_be/EW36yg_NVLpNh8ZnxMWDRMMBcjk06wgTcNTkrhaFus4-AA?e=REQoy7>. All the files of the PDFHummus library are in the exts folder. I have also attached a screenshot of the error message that I keep on getting.
I have to warn you that because of the fact I kept on getting errors I am currently using absolute paths to link the library and not yet relative paths.
Thank you in advance for helping me!

**Comment by galkahana** [comment]
wow. it's been ages since i opened visual studio haha.

ok. i think i understand what's wrong.

In Configuration Properties->Linker->Input under "Additional Dependencies" you put the path to the lib folder. like `D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib`
this is the "lib" in "lib.obj". you see, what you should be putting here is the complete list of the libraries/dlls you link against and a path wont do. you got to include the actual file names. so instead of the folder path list all libs like this:

```
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\PDFWriter.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\FreeType.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\LibAesgm.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\LibJpeg.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\LibPng.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\LibTiff.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\PDFWriter.lib
D:\userFolder\research\filehandler\Filehandler\Filehandler\Filehandler\exts\PDF-Writer-master\etc\install\lib\Zlib.lib
```

I tried this and linking succeeded and i was able to run yr program.
I don't know if there's an option to do like what you attempted, which is to just include all files under a folder in Visual Studio.

Let me know if my explanation is not clear or doesn't otherwise solve the problem you reported.
