### ISSUE TITLE
Links are removed when documents are merged

### ISSUE THREAD

**Issue by Dykson** [galkahana/PDF-Writer#231]
When combining 2 documents, I found that the web links disappear. Will it work in the future or am I doing something wrong?

```
pdfWriter.StartPDF(out.pdf, ePDFVersion17); 
pdfWriter.AppendPDFPagesFromPDF("1.pdf", PDFPageRange()); 
pdfWriter.AppendPDFPagesFromPDF("2.pdf", PDFPageRange()); 
pdfWriter.EndPDF(); 

```
And tell me, is there a way to replace certain links?

(build msvc 2019 x64)

**Comment by galkahana** [comment]
it's sort of by design.
appending pages only appends their graphic data. no interactive. supposed to function like image embedding.
you can extend the copying code to also add links (in PDF lingua they are part of "annotations").

here's an essay discussing how to do it with example code:
https://www.pdfhummus.com/post/45501619928/copying-pages-with-comments
while it deals with comments, the code just copies annotations in general, so - comments, links etc.

**Comment by Dykson** [comment]
[CopyingPagesWithComments.cpp](https://github.com/galkahana/PDFWriterSamples/blob/master/CopyingPagesWithComments/CopyingPagesWithComments.cpp) works great with a simple pdf file MakingComments.pdf from the example. If you change the pdf file to your own, an exception will be thrown. I tried different files. It works terribly for me

**Comment by galkahana** [comment]
if you're willing to send me a sample i can probably see what the problem is and provide you a working example.

**Comment by Dykson** [comment]
[a1.pdf](https://github.com/galkahana/PDF-Writer/files/13399589/a1.pdf)

Crashes [on line 116](https://github.com/galkahana/PDFWriterSamples/blob/master/CopyingPagesWithComments/CopyingPagesWithComments.cpp)
`116.  EStatusCodeAndObjectIDType result = copyingContext->CopyObject(annotationReference->mObjectID);`

**Comment by galkahana** [comment]
Im gonna need a sample to tell why theres a problem and correct it

**Comment by galkahana** [comment]
hmmm.
I wasn't able to recreate the crash.
created a branch with the code and file as a test - [galk.named_dests](https://github.com/galkahana/PDF-Writer/tree/galk.named_dests). created a test with the code of copyingpageswithcomments named [AppendWithAnnotations](https://github.com/galkahana/PDF-Writer/blob/galk.named_dests/PDFWriterTesting/AppendWithAnnotations.cpp).

generated this output file:
[CopyingPagesWithComments.pdf](https://github.com/galkahana/PDF-Writer/files/13401008/CopyingPagesWithComments.pdf)

outside, web, links seem to work. other links - those that got into the file itself don't. ill explain why soon.

As to the error that you experienced, it might be that you have another file that fails on this if somehow the annotation is embedded into the annotation dictionary instead of only being referred to. the code can be arranged to solve this better (either by allowing direct references, or copying the annotation to a new indirect object)...but yeah it is a bit more sophisticated.

as for the problem i saw, that the links don't work, is partly why i didn't bother with links when embedding individual pages. you see, internal links (named destinations) are a global PDF file object, which means it doesnt sit in the page, but rather in the global PDF object (the catalog). so copying individual pages ain't gonna be enough, and any implementation which potentially copy just some of the pages will be faulty.

there are several paths out of this depending what's the end game with embedding the pages in a new document. If this is just one document and you mean to provide overlay on top of it...then best is to create a modified version of the PDF file instead of appending its pages one by one. if you want to merge multiple PDFs, then you will have to write a more sophisticated coed to allow merging such things as named destinations.

in any case there's 2 things here i saw:
- the problem you saw that i wasn't able to recreate - maybe you were using a different file? in that case please provide it to me...maybe it's still a simpler scenario (like the one for comments, or if the links are just plain urls).
- the problem i saw, which is simply because the code is not smart enough to handle named destinations...in which maybe tell me a bit more about what you intend to do with the PDF and we could consider the simplest solution to fit.

Cheers,
Gal.

**Comment by Dykson** [comment]
Yes, you're right, I rechecked the files and sent them to the mail

**Comment by galkahana** [comment]
sent back a response via email.

**Comment by Dykson** [comment]
Well, the proposed fixes worked, thank you
