### ISSUE TITLE
How to get baseline to baseline distance (new line advance)?

### ISSUE THREAD

**Issue by raimundomartins** [galkahana/PDF-Writer#41]
Currently, I'm using freetype directly like so:
```
float font_size = 14.;
PDFUsedFont *font = pdfWriter.GetFontForFile("font.ttf");
FT_Face face = *font->GetFreeTypeFont();
float newline_height = font_size * face->height / face->units_per_EM;
```
But I'd rather use PDFUsedFont, and never mess with freetype (what if some other non-freetype format comes along, or what if this has some quirks which doesn't work with all fonts?). Is it possible to use only PDF-Writer objects to achieve this?

Also, PDFUsedFont::CalculateTextDimensions receives a long as font size, but Tf operator receives a double. Shouldn't these be consistent?

**Comment by galkahana** [comment]
That's not too bad to use the free type font directly. Hummus is kind of relying on free type to get basic font data and do the character->glyph encoding. been that way for 5 years and i dont currently intend to change it.

As for baseline to baseline spacing, from what i know (relying on indesign and my own work history), the distance normally used is not so much a function of the font, and is solely dependent on the font size.
normal line height is simply 1.2 * font-size. designers sometimes change that manually to some other value.

The only thing then that is relying on the font is the first line distance from the box top - something especially important when using a border on the box. You would normally want the text ascent, so that you can realize where to put the first line.   
Indesign has multiple options as to what to use for this "ascent", but us normal people can just use the line ascent. The helpful `CalculateTextDimensions` will give you that through yMax. Note that xMax may come in handy too, more than width, because the first char might have some advance so its start a little later than 0 (width will give you that without that advance).      
If you want some more clever ascent than consider using:
````
BoolAndFTShort GetCapHeight(); // aligned to pdf metrics
BoolAndFTShort GetxHeight(); // aligned to pdf metrics
````
of the `FreeTypeFaceWrapper` that you get via `GetFreeTypeFont`.

as for long vs. float. yeah yeah...i probably should allow passing float to `CalculateTextDimensions`. after all half font sizes are an existing thing. which is why its allows in tf. thanks.

**Comment by raimundomartins** [comment]
> Hummus is kind of relying on free type to get basic font data and do the character->glyph encoding.

I wasn't suggesting to change Hummus to not use freetype (although IIRC somewhere in the wiki you state that this could easily change if requested by someone), I just wanted to not depend on freetype directly in my code.

In fact, I'd even prefer that Hummus' headers would not depend on freetype, as it would be easier for multi-platform builds. Would you accept a pull request that would make those changes? (Not commiting on doing them, nor setting a date. I just want to know how you feel about it)

Indeed, after  [reading more about it](https://tex.stackexchange.com/questions/30073/why-is-the-linespread-factor-as-it-is), it seems I had the wrong idea about line spacing. But still, you brought the issue of ascent (which I'll likely will need later), and I have problems with both of your suggestions:

- `CalculateTextDimensions` naturally depends on the text. Both text and font are unknown at compile-time, so unless I do this at run-time for the whole charset (ugly), this could lead to uncertain results.
- `GetCapHeight()` is not very useful (I think) because it doesn't represent the biggest char in the font. Think latin characters, which will definitely appear (`Á` is bigger than `H`)
- `GetxHeight()`: how is this useful for the ascent? (no, really, no sarcasm, I have no idea how to use this)

Another thing: many values in freetype are 0. An example of which is `FT_Face::ascender`, which could to be very useful for the discussion. Is this normal?

**Comment by galkahana** [comment]
RE code contribs. sure, go for it.

RE ascent. not sure that i understand your discourse, but what i've been doing is something similar to `calculateTextDimensions` xMax on the line on the text that's supposed to go at the first line.
If you are looking at something else, then just build whatever is appropriate there.

RE freetype values, donnow. could be.

Gal.

**Comment by raimundomartins** [comment]
I think you meant `yMax` there, since we're talking about ascent.
Anyway, I guess I'll use freetype directly, no big harm, and now I've got some nice keywords to search for.

Thanks again! :-)
