### ISSUE TITLE
Parsing fails

### ISSUE THREAD

**Issue by sagendejonge** [galkahana/PDF-Writer#86]
Hi again,

I'm getting parsing errors with the attached two files.  One of them appears linearized and the other from distiller.  Below is a simple bit of code used to show the issue.  Both output "Failed at start parsing".

[test3.pdf](https://github.com/galkahana/PDF-Writer/files/787024/test3.pdf)
[test4.pdf](https://github.com/galkahana/PDF-Writer/files/787025/test4.pdf)

``` c++
#include <iostream>
#include <fstream>
#include <string>
#include "PDFHummus/PDFParser.h"
#include "PDFHummus/InputFile.h"
#include "PDFHummus/EStatusCode.h"

using namespace std;
using namespace PDFHummus;

void openPDF(char *path) {
    PDFParser parser;
    InputFile pdfFile;
    EStatusCode status = pdfFile.OpenFile(path);
    if (status != eSuccess) {
        std::cout << "Invalid path: " << path << std::endl;
        return;
    }

    status = parser.StartPDFParsing(pdfFile.GetInputStream());
    if (status != eSuccess) {
        std::cout << "Failed at start parsing" << std::endl;
        return;
    }
}

int main(int count, char* args[]) {
    if (count < 2) {
        cerr << "PDF file required" << endl;
        return 1;
    }

    if (count == 2) {
        openPDF(args[1]);
    }

    return 0;
}
```

**Comment by galkahana** [comment]
oh this is lovely. i'm gonna have some fun with this

**Comment by galkahana** [comment]
k. both of these files have corrupted content post their %%eof.
Acrobat is flexible about these kind of things, hummus less so. you know, it's all about performance here, so forgiveness and validations are out, most of the time.
anyways. isn't that much of problem. i added code to look %%eof from end, instead of just assuming its in the end.

this one corrects it (well, first one that has the whole thing) - 6870068abbc53b3d78558ce4f432814449ddc5e0.

cheers,
Gal.

**Comment by sagendejonge** [comment]
Just tested, works beautifully :)  Thanks a bunch!
